### ISSUE TITLE
Error when installing on fedora 

### ISSUE THREAD

**Issue by yodatak** [vaulttec/ansible-role-zsh#2]
TASK [vaulttec.zsh : Install required packages] ********************************
failed: [localhost] (item=[u'zsh', u'git']) => {"failed": true, "item": ["zsh", "git"], "msg": "unsupported parameter for module: update_cache"}

**Comment by yodatak** [comment]
I pass the error on removing  update_cache in main.yml in task folder 

- name: Install required packages
  become: yes
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: "{{ zsh_dependencies }}"
  tags: packages

**Comment by yodatak** [comment]
And it don't check the presence of python2-dnf and libselinux-python in fedora
python2-dnf ` is not installed, but it is required for the Ansible dnf module."}

**Comment by tjuerge** [comment]
> And it don't check the presence of python2-dnf and libselinux-python in fedora

Yes, this role assumes that all the platform-specific requirements for running Ansible are satisfied. So it doesn't check for python and the required python libs.
